"""udev-rules generator + installer for supported SDR / rotator hardware.

"My SDR doesn't show up" is the #1 first-experience friction point in the SDR
ecosystem — a fresh USB device is owned by ``root`` and a non-root process
cannot open it. The fix is a udev rule granting the right permissions; this
module generates that rule for every supported device and installs it.

Everything here is pure Python (a Pydantic model + string rendering + a
``subprocess`` install path) — no vendor SDK, importable on a base install.

The ``rfdf hw udev`` CLI sub-commands (``list`` / ``generate`` / ``install``)
wrap these helpers.
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

from pydantic import BaseModel, field_validator

#: Where the generated rules are installed.
DEFAULT_RULES_PATH = Path("/etc/udev/rules.d/70-rfdf.rules")


class UdevRule(BaseModel):
    """A single udev rule for one USB device.

    Attributes:
        vendor_id: USB vendor ID, 4 hex digits (e.g. ``"2500"`` for Ettus).
        product_id: USB product ID, 4 hex digits.
        symlink: ``/dev`` symlink name; ``%n`` expands to the kernel number.
        mode: Octal device-node permission mode.
        description: Human-readable device name.
    """

    vendor_id: str
    product_id: str
    symlink: str
    mode: str = "0666"
    description: str

    @field_validator("vendor_id", "product_id")
    @classmethod
    def _check_hex_id(cls, value: str) -> str:
        """Reject a USB ID that is not 4 lowercase hex digits."""
        normalised = value.strip().lower()
        if len(normalised) != 4 or any(c not in "0123456789abcdef" for c in normalised):
            raise ValueError(f"USB ID must be 4 hex digits, got {value!r}")
        return normalised

    @field_validator("mode")
    @classmethod
    def _check_mode(cls, value: str) -> str:
        """Reject a non-octal permission mode."""
        try:
            int(value, 8)
        except ValueError as exc:
            raise ValueError(f"mode must be octal, got {value!r}") from exc
        return value


#: Every device rfdf knows how to permission. Site-agnostic — no serials.
KNOWN_DEVICES: list[UdevRule] = [
    UdevRule(vendor_id="2500", product_id="0020", symlink="b210_%n", description="Ettus USRP B210"),
    UdevRule(
        vendor_id="2500",
        product_id="0021",
        symlink="b200mini_%n",
        description="Ettus USRP B200mini",
    ),
    UdevRule(vendor_id="2500", product_id="0022", symlink="b200_%n", description="Ettus USRP B200"),
    UdevRule(
        vendor_id="0bda",
        product_id="2838",
        symlink="rtl_sdr_%n",
        description="RTL2832U + R820T2 (RTL-SDR)",
    ),
    UdevRule(
        vendor_id="1d50",
        product_id="6089",
        symlink="hackrf_%n",
        description="Great Scott Gadgets HackRF One",
    ),
    UdevRule(
        vendor_id="0456",
        product_id="b673",
        symlink="pluto_%n",
        description="Analog Devices ADALM-PLUTO",
    ),
]


def render_rule(rule: UdevRule) -> str:
    """Render one :class:`UdevRule` as a udev rule line."""
    return (
        f'SUBSYSTEM=="usb", '
        f'ATTRS{{idVendor}}=="{rule.vendor_id}", '
        f'ATTRS{{idProduct}}=="{rule.product_id}", '
        f'MODE="{rule.mode}", SYMLINK+="{rule.symlink}"  '
        f"# {rule.description}"
    )


def render_rules_file(rules: list[UdevRule] | None = None) -> str:
    """Render the full ``70-rfdf.rules`` file content.

    Args:
        rules: Rules to render; defaults to :data:`KNOWN_DEVICES`.

    Returns:
        The complete rules-file text, with a generated-by header.
    """
    selected = rules if rules is not None else KNOWN_DEVICES
    header = [
        "# udev rules for rfdf-supported SDR / rotator hardware.",
        "# Generated by `rfdf hw udev generate` — do not edit by hand.",
        "# Grants non-root access so rfdf backends can open the device.",
        "",
    ]
    body = [render_rule(rule) for rule in selected]
    return "\n".join(header + body) + "\n"


def is_root() -> bool:
    """Return whether the current process has root privileges."""
    return hasattr(os, "geteuid") and os.geteuid() == 0


def install_rules(
    content: str,
    *,
    path: Path = DEFAULT_RULES_PATH,
    reload: bool = True,
) -> str:
    """Write the rules file and reload the udev database.

    Args:
        content: Rules-file text (from :func:`render_rules_file`).
        path: Destination path.
        reload: When True, run ``udevadm control --reload-rules`` +
            ``udevadm trigger`` after writing.

    Returns:
        A one-line human-readable result summary.

    Raises:
        PermissionError: If the process cannot write ``path`` (needs root).
    """
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    except PermissionError as exc:
        raise PermissionError(
            f"cannot write {path} — udev-rule installation requires root; re-run with sudo."
        ) from exc
    if reload:
        for args in (
            ["udevadm", "control", "--reload-rules"],
            ["udevadm", "trigger", "--subsystem-match=usb"],
        ):
            try:
                subprocess.run(args, check=True, capture_output=True, timeout=15)
            except (OSError, subprocess.SubprocessError) as exc:
                return (
                    f"wrote {path}, but `{' '.join(args)}` failed ({exc}); "
                    f"reload udev manually or replug the device."
                )
    return f"installed {len(content.splitlines())} lines to {path}; udev reloaded."


__all__ = [
    "DEFAULT_RULES_PATH",
    "KNOWN_DEVICES",
    "UdevRule",
    "install_rules",
    "is_root",
    "render_rule",
    "render_rules_file",
]
